/*
 * This file is generated by jOOQ.
 */
package au.edu.unimelb.crbilby.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * The table <code>cr_db.case</code>.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Case implements Serializable {

    private static final long serialVersionUID = 1523163244;

    private Integer   id;
    private String    profile;
    private Integer   type;
    private String    address;
    private Timestamp date;
    private String    description;
    private Double    longitude;
    private Double    latitude;
    private Integer   post;
    private Integer   isClosed;

    public Case() {}

    public Case(Case value) {
        this.id = value.id;
        this.profile = value.profile;
        this.type = value.type;
        this.address = value.address;
        this.date = value.date;
        this.description = value.description;
        this.longitude = value.longitude;
        this.latitude = value.latitude;
        this.post = value.post;
        this.isClosed = value.isClosed;
    }

    public Case(
        Integer   id,
        String    profile,
        Integer   type,
        String    address,
        Timestamp date,
        String    description,
        Double    longitude,
        Double    latitude,
        Integer   post,
        Integer   isClosed
    ) {
        this.id = id;
        this.profile = profile;
        this.type = type;
        this.address = address;
        this.date = date;
        this.description = description;
        this.longitude = longitude;
        this.latitude = latitude;
        this.post = post;
        this.isClosed = isClosed;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getProfile() {
        return this.profile;
    }

    public void setProfile(String profile) {
        this.profile = profile;
    }

    public Integer getType() {
        return this.type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Timestamp getDate() {
        return this.date;
    }

    public void setDate(Timestamp date) {
        this.date = date;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Double getLongitude() {
        return this.longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public Double getLatitude() {
        return this.latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Integer getPost() {
        return this.post;
    }

    public void setPost(Integer post) {
        this.post = post;
    }

    public Integer getIsClosed() {
        return this.isClosed;
    }

    public void setIsClosed(Integer isClosed) {
        this.isClosed = isClosed;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Case other = (Case) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (profile == null) {
            if (other.profile != null)
                return false;
        }
        else if (!profile.equals(other.profile))
            return false;
        if (type == null) {
            if (other.type != null)
                return false;
        }
        else if (!type.equals(other.type))
            return false;
        if (address == null) {
            if (other.address != null)
                return false;
        }
        else if (!address.equals(other.address))
            return false;
        if (date == null) {
            if (other.date != null)
                return false;
        }
        else if (!date.equals(other.date))
            return false;
        if (description == null) {
            if (other.description != null)
                return false;
        }
        else if (!description.equals(other.description))
            return false;
        if (longitude == null) {
            if (other.longitude != null)
                return false;
        }
        else if (!longitude.equals(other.longitude))
            return false;
        if (latitude == null) {
            if (other.latitude != null)
                return false;
        }
        else if (!latitude.equals(other.latitude))
            return false;
        if (post == null) {
            if (other.post != null)
                return false;
        }
        else if (!post.equals(other.post))
            return false;
        if (isClosed == null) {
            if (other.isClosed != null)
                return false;
        }
        else if (!isClosed.equals(other.isClosed))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.profile == null) ? 0 : this.profile.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        result = prime * result + ((this.address == null) ? 0 : this.address.hashCode());
        result = prime * result + ((this.date == null) ? 0 : this.date.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.longitude == null) ? 0 : this.longitude.hashCode());
        result = prime * result + ((this.latitude == null) ? 0 : this.latitude.hashCode());
        result = prime * result + ((this.post == null) ? 0 : this.post.hashCode());
        result = prime * result + ((this.isClosed == null) ? 0 : this.isClosed.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Case (");

        sb.append(id);
        sb.append(", ").append(profile);
        sb.append(", ").append(type);
        sb.append(", ").append(address);
        sb.append(", ").append(date);
        sb.append(", ").append(description);
        sb.append(", ").append(longitude);
        sb.append(", ").append(latitude);
        sb.append(", ").append(post);
        sb.append(", ").append(isClosed);

        sb.append(")");
        return sb.toString();
    }
}
