/*
 * This file is generated by jOOQ.
 */
package au.edu.unimelb.crbilby.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * The table <code>cr_db.case_other_crimes</code>.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CaseOtherCrimes implements Serializable {

    private static final long serialVersionUID = 1273730187;

    private Integer id;
    private String  crime;

    public CaseOtherCrimes() {}

    public CaseOtherCrimes(CaseOtherCrimes value) {
        this.id = value.id;
        this.crime = value.crime;
    }

    public CaseOtherCrimes(
        Integer id,
        String  crime
    ) {
        this.id = id;
        this.crime = crime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCrime() {
        return this.crime;
    }

    public void setCrime(String crime) {
        this.crime = crime;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CaseOtherCrimes other = (CaseOtherCrimes) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (crime == null) {
            if (other.crime != null)
                return false;
        }
        else if (!crime.equals(other.crime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.crime == null) ? 0 : this.crime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CaseOtherCrimes (");

        sb.append(id);
        sb.append(", ").append(crime);

        sb.append(")");
        return sb.toString();
    }
}
