/*
 * This file is generated by jOOQ.
 */
package au.edu.unimelb.crbilby.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * The table <code>cr_db.case_notes</code>.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CaseNotes implements Serializable {

    private static final long serialVersionUID = -1607706886;

    private Integer   id;
    private Integer   case_;
    private String    profile;
    private Timestamp timestamp;
    private String    note;

    public CaseNotes() {}

    public CaseNotes(CaseNotes value) {
        this.id = value.id;
        this.case_ = value.case_;
        this.profile = value.profile;
        this.timestamp = value.timestamp;
        this.note = value.note;
    }

    public CaseNotes(
        Integer   id,
        Integer   case_,
        String    profile,
        Timestamp timestamp,
        String    note
    ) {
        this.id = id;
        this.case_ = case_;
        this.profile = profile;
        this.timestamp = timestamp;
        this.note = note;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCase() {
        return this.case_;
    }

    public void setCase(Integer case_) {
        this.case_ = case_;
    }

    public String getProfile() {
        return this.profile;
    }

    public void setProfile(String profile) {
        this.profile = profile;
    }

    public Timestamp getTimestamp() {
        return this.timestamp;
    }

    public void setTimestamp(Timestamp timestamp) {
        this.timestamp = timestamp;
    }

    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CaseNotes other = (CaseNotes) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (case_ == null) {
            if (other.case_ != null)
                return false;
        }
        else if (!case_.equals(other.case_))
            return false;
        if (profile == null) {
            if (other.profile != null)
                return false;
        }
        else if (!profile.equals(other.profile))
            return false;
        if (timestamp == null) {
            if (other.timestamp != null)
                return false;
        }
        else if (!timestamp.equals(other.timestamp))
            return false;
        if (note == null) {
            if (other.note != null)
                return false;
        }
        else if (!note.equals(other.note))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.case_ == null) ? 0 : this.case_.hashCode());
        result = prime * result + ((this.profile == null) ? 0 : this.profile.hashCode());
        result = prime * result + ((this.timestamp == null) ? 0 : this.timestamp.hashCode());
        result = prime * result + ((this.note == null) ? 0 : this.note.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CaseNotes (");

        sb.append(id);
        sb.append(", ").append(case_);
        sb.append(", ").append(profile);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(note);

        sb.append(")");
        return sb.toString();
    }
}
