/*
 * This file is generated by jOOQ.
 */
package au.edu.unimelb.crbilby.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * The table <code>cr_db.case_evidence</code>.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CaseEvidence implements Serializable {

    private static final long serialVersionUID = -432925980;

    private Integer id;
    private Integer case_;
    private String  evidence;

    public CaseEvidence() {}

    public CaseEvidence(CaseEvidence value) {
        this.id = value.id;
        this.case_ = value.case_;
        this.evidence = value.evidence;
    }

    public CaseEvidence(
        Integer id,
        Integer case_,
        String  evidence
    ) {
        this.id = id;
        this.case_ = case_;
        this.evidence = evidence;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCase() {
        return this.case_;
    }

    public void setCase(Integer case_) {
        this.case_ = case_;
    }

    public String getEvidence() {
        return this.evidence;
    }

    public void setEvidence(String evidence) {
        this.evidence = evidence;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CaseEvidence other = (CaseEvidence) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (case_ == null) {
            if (other.case_ != null)
                return false;
        }
        else if (!case_.equals(other.case_))
            return false;
        if (evidence == null) {
            if (other.evidence != null)
                return false;
        }
        else if (!evidence.equals(other.evidence))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.case_ == null) ? 0 : this.case_.hashCode());
        result = prime * result + ((this.evidence == null) ? 0 : this.evidence.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CaseEvidence (");

        sb.append(id);
        sb.append(", ").append(case_);
        sb.append(", ").append(evidence);

        sb.append(")");
        return sb.toString();
    }
}
