/*
 * This file is generated by jOOQ.
 */
package au.edu.unimelb.crbilby.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * The table <code>cr_db.crime_type</code>.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CrimeType implements Serializable {

    private static final long serialVersionUID = 1047212609;

    private Integer id;
    private String  type;

    public CrimeType() {}

    public CrimeType(CrimeType value) {
        this.id = value.id;
        this.type = value.type;
    }

    public CrimeType(
        Integer id,
        String  type
    ) {
        this.id = id;
        this.type = type;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CrimeType other = (CrimeType) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (type == null) {
            if (other.type != null)
                return false;
        }
        else if (!type.equals(other.type))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CrimeType (");

        sb.append(id);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
