/*
 * This file is generated by jOOQ.
 */
package au.edu.unimelb.crbilby.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * The table <code>cr_db.Escalate_level</code>.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EscalateLevel implements Serializable {

    private static final long serialVersionUID = 395977599;

    private Integer id;
    private String  level;

    public EscalateLevel() {}

    public EscalateLevel(EscalateLevel value) {
        this.id = value.id;
        this.level = value.level;
    }

    public EscalateLevel(
        Integer id,
        String  level
    ) {
        this.id = id;
        this.level = level;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getLevel() {
        return this.level;
    }

    public void setLevel(String level) {
        this.level = level;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final EscalateLevel other = (EscalateLevel) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (level == null) {
            if (other.level != null)
                return false;
        }
        else if (!level.equals(other.level))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.level == null) ? 0 : this.level.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EscalateLevel (");

        sb.append(id);
        sb.append(", ").append(level);

        sb.append(")");
        return sb.toString();
    }
}
