/*
 * This file is generated by jOOQ.
 */
package au.edu.unimelb.crbilby.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * The table <code>cr_db.lea_post</code>.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LeaPost implements Serializable {

    private static final long serialVersionUID = -1119151539;

    private String  profile;
    private Integer post;

    public LeaPost() {}

    public LeaPost(LeaPost value) {
        this.profile = value.profile;
        this.post = value.post;
    }

    public LeaPost(
        String  profile,
        Integer post
    ) {
        this.profile = profile;
        this.post = post;
    }

    public String getProfile() {
        return this.profile;
    }

    public void setProfile(String profile) {
        this.profile = profile;
    }

    public Integer getPost() {
        return this.post;
    }

    public void setPost(Integer post) {
        this.post = post;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final LeaPost other = (LeaPost) obj;
        if (profile == null) {
            if (other.profile != null)
                return false;
        }
        else if (!profile.equals(other.profile))
            return false;
        if (post == null) {
            if (other.post != null)
                return false;
        }
        else if (!post.equals(other.post))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.profile == null) ? 0 : this.profile.hashCode());
        result = prime * result + ((this.post == null) ? 0 : this.post.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LeaPost (");

        sb.append(profile);
        sb.append(", ").append(post);

        sb.append(")");
        return sb.toString();
    }
}
