/*
 * This file is generated by jOOQ.
 */
package au.edu.unimelb.crbilby.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * The table <code>cr_db.post</code>.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Post implements Serializable {

    private static final long serialVersionUID = 89384528;

    private Integer id;
    private String  name;
    private Integer escalateLvl;
    private String  chief;

    public Post() {}

    public Post(Post value) {
        this.id = value.id;
        this.name = value.name;
        this.escalateLvl = value.escalateLvl;
        this.chief = value.chief;
    }

    public Post(
        Integer id,
        String  name,
        Integer escalateLvl,
        String  chief
    ) {
        this.id = id;
        this.name = name;
        this.escalateLvl = escalateLvl;
        this.chief = chief;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getEscalateLvl() {
        return this.escalateLvl;
    }

    public void setEscalateLvl(Integer escalateLvl) {
        this.escalateLvl = escalateLvl;
    }

    public String getChief() {
        return this.chief;
    }

    public void setChief(String chief) {
        this.chief = chief;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Post other = (Post) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        if (escalateLvl == null) {
            if (other.escalateLvl != null)
                return false;
        }
        else if (!escalateLvl.equals(other.escalateLvl))
            return false;
        if (chief == null) {
            if (other.chief != null)
                return false;
        }
        else if (!chief.equals(other.chief))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.escalateLvl == null) ? 0 : this.escalateLvl.hashCode());
        result = prime * result + ((this.chief == null) ? 0 : this.chief.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Post (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(escalateLvl);
        sb.append(", ").append(chief);

        sb.append(")");
        return sb.toString();
    }
}
