// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:2447e2ed-b76f-4b21-bef7-eb16b392a847",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_iRsX61dqY",
    "aws_user_pools_web_client_id": "3h0aabksj2g1710g2mf8g6ds0o",
    "aws_user_files_s3_bucket": "sign67cb05fde0894aad961a9b532d5a7a8b",
    "aws_user_files_s3_bucket_region": "ap-southeast-2"
};


export default awsmobile;
