/*
 * This file is generated by jOOQ.
 */
package au.edu.unimelb.crbilby.db.tables;


import au.edu.unimelb.crbilby.db.CrDb;
import au.edu.unimelb.crbilby.db.tables.records.CaseNotesRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


/**
 * The table <code>cr_db.case_notes</code>.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CaseNotes extends TableImpl<CaseNotesRecord> {

    private static final long serialVersionUID = 178555271;

    /**
     * The reference instance of <code>cr_db.case_notes</code>
     */
    public static final CaseNotes CASE_NOTES = new CaseNotes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CaseNotesRecord> getRecordType() {
        return CaseNotesRecord.class;
    }

    /**
     * The column <code>cr_db.case_notes.id</code>.
     */
    public final TableField<CaseNotesRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>cr_db.case_notes.case</code>.
     */
    public final TableField<CaseNotesRecord, Integer> CASE = createField("case", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>cr_db.case_notes.profile</code>.
     */
    public final TableField<CaseNotesRecord, String> PROFILE = createField("profile", org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>cr_db.case_notes.timestamp</code>.
     */
    public final TableField<CaseNotesRecord, Timestamp> TIMESTAMP = createField("timestamp", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>cr_db.case_notes.note</code>.
     */
    public final TableField<CaseNotesRecord, String> NOTE = createField("note", org.jooq.impl.SQLDataType.VARCHAR(1024).nullable(false), this, "");

    /**
     * Create a <code>cr_db.case_notes</code> table reference
     */
    public CaseNotes() {
        this(DSL.name("case_notes"), null);
    }

    /**
     * Create an aliased <code>cr_db.case_notes</code> table reference
     */
    public CaseNotes(String alias) {
        this(DSL.name(alias), CASE_NOTES);
    }

    /**
     * Create an aliased <code>cr_db.case_notes</code> table reference
     */
    public CaseNotes(Name alias) {
        this(alias, CASE_NOTES);
    }

    private CaseNotes(Name alias, Table<CaseNotesRecord> aliased) {
        this(alias, aliased, null);
    }

    private CaseNotes(Name alias, Table<CaseNotesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return CrDb.CR_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CaseNotesRecord, Integer> getIdentity() {
        return Internal.createIdentity(au.edu.unimelb.crbilby.db.tables.CaseNotes.CASE_NOTES, au.edu.unimelb.crbilby.db.tables.CaseNotes.CASE_NOTES.ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CaseNotesRecord> getPrimaryKey() {
        return Internal.createUniqueKey(au.edu.unimelb.crbilby.db.tables.CaseNotes.CASE_NOTES, "KEY_case_notes_PRIMARY", au.edu.unimelb.crbilby.db.tables.CaseNotes.CASE_NOTES.ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CaseNotesRecord>> getKeys() {
        return Arrays.<UniqueKey<CaseNotesRecord>>asList(
              Internal.createUniqueKey(au.edu.unimelb.crbilby.db.tables.CaseNotes.CASE_NOTES, "KEY_case_notes_PRIMARY", au.edu.unimelb.crbilby.db.tables.CaseNotes.CASE_NOTES.ID)
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CaseNotes as(String alias) {
        return new CaseNotes(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CaseNotes as(Name alias) {
        return new CaseNotes(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CaseNotes rename(String name) {
        return new CaseNotes(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CaseNotes rename(Name name) {
        return new CaseNotes(name, null);
    }
}
