/*
 * This file is generated by jOOQ.
 */
package au.edu.unimelb.crbilby.db.tables;


import au.edu.unimelb.crbilby.db.CrDb;
import au.edu.unimelb.crbilby.db.tables.records.CrimeTypeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


/**
 * The table <code>cr_db.crime_type</code>.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CrimeType extends TableImpl<CrimeTypeRecord> {

    private static final long serialVersionUID = -363851709;

    /**
     * The reference instance of <code>cr_db.crime_type</code>
     */
    public static final CrimeType CRIME_TYPE = new CrimeType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CrimeTypeRecord> getRecordType() {
        return CrimeTypeRecord.class;
    }

    /**
     * The column <code>cr_db.crime_type.id</code>.
     */
    public final TableField<CrimeTypeRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>cr_db.crime_type.type</code>.
     */
    public final TableField<CrimeTypeRecord, String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * Create a <code>cr_db.crime_type</code> table reference
     */
    public CrimeType() {
        this(DSL.name("crime_type"), null);
    }

    /**
     * Create an aliased <code>cr_db.crime_type</code> table reference
     */
    public CrimeType(String alias) {
        this(DSL.name(alias), CRIME_TYPE);
    }

    /**
     * Create an aliased <code>cr_db.crime_type</code> table reference
     */
    public CrimeType(Name alias) {
        this(alias, CRIME_TYPE);
    }

    private CrimeType(Name alias, Table<CrimeTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private CrimeType(Name alias, Table<CrimeTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return CrDb.CR_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CrimeTypeRecord, Integer> getIdentity() {
        return Internal.createIdentity(au.edu.unimelb.crbilby.db.tables.CrimeType.CRIME_TYPE, au.edu.unimelb.crbilby.db.tables.CrimeType.CRIME_TYPE.ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CrimeTypeRecord> getPrimaryKey() {
        return Internal.createUniqueKey(au.edu.unimelb.crbilby.db.tables.CrimeType.CRIME_TYPE, "KEY_crime_type_PRIMARY", au.edu.unimelb.crbilby.db.tables.CrimeType.CRIME_TYPE.ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CrimeTypeRecord>> getKeys() {
        return Arrays.<UniqueKey<CrimeTypeRecord>>asList(
              Internal.createUniqueKey(au.edu.unimelb.crbilby.db.tables.CrimeType.CRIME_TYPE, "KEY_crime_type_PRIMARY", au.edu.unimelb.crbilby.db.tables.CrimeType.CRIME_TYPE.ID)
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrimeType as(String alias) {
        return new CrimeType(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrimeType as(Name alias) {
        return new CrimeType(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CrimeType rename(String name) {
        return new CrimeType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CrimeType rename(Name name) {
        return new CrimeType(name, null);
    }
}
