/*
 * This file is generated by jOOQ.
 */
package au.edu.unimelb.crbilby.db.tables.records;


import au.edu.unimelb.crbilby.db.tables.CaseOtherCrimes;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * The table <code>cr_db.case_other_crimes</code>.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CaseOtherCrimesRecord extends UpdatableRecordImpl<CaseOtherCrimesRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1309033679;

    /**
     * Setter for <code>cr_db.case_other_crimes.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>cr_db.case_other_crimes.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>cr_db.case_other_crimes.crime</code>.
     */
    public void setCrime(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cr_db.case_other_crimes.crime</code>.
     */
    public String getCrime() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CaseOtherCrimes.CASE_OTHER_CRIMES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CaseOtherCrimes.CASE_OTHER_CRIMES.CRIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCrime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCrime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CaseOtherCrimesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CaseOtherCrimesRecord value2(String value) {
        setCrime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CaseOtherCrimesRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CaseOtherCrimesRecord
     */
    public CaseOtherCrimesRecord() {
        super(CaseOtherCrimes.CASE_OTHER_CRIMES);
    }

    /**
     * Create a detached, initialised CaseOtherCrimesRecord
     */
    public CaseOtherCrimesRecord(Integer id, String crime) {
        super(CaseOtherCrimes.CASE_OTHER_CRIMES);

        set(0, id);
        set(1, crime);
    }
}
