/*
 * This file is generated by jOOQ.
 */
package au.edu.unimelb.crbilby.db.tables.records;


import au.edu.unimelb.crbilby.db.tables.CaseEvidence;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * The table <code>cr_db.case_evidence</code>.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CaseEvidenceRecord extends UpdatableRecordImpl<CaseEvidenceRecord> implements Record3<Integer, Integer, String> {

    private static final long serialVersionUID = -883840659;

    /**
     * Setter for <code>cr_db.case_evidence.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>cr_db.case_evidence.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>cr_db.case_evidence.case</code>.
     */
    public void setCase(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>cr_db.case_evidence.case</code>.
     */
    public Integer getCase() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>cr_db.case_evidence.evidence</code>.
     */
    public void setEvidence(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>cr_db.case_evidence.evidence</code>.
     */
    public String getEvidence() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CaseEvidence.CASE_EVIDENCE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return CaseEvidence.CASE_EVIDENCE.CASE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CaseEvidence.CASE_EVIDENCE.EVIDENCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getCase();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getEvidence();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCase();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEvidence();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CaseEvidenceRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CaseEvidenceRecord value2(Integer value) {
        setCase(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CaseEvidenceRecord value3(String value) {
        setEvidence(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CaseEvidenceRecord values(Integer value1, Integer value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CaseEvidenceRecord
     */
    public CaseEvidenceRecord() {
        super(CaseEvidence.CASE_EVIDENCE);
    }

    /**
     * Create a detached, initialised CaseEvidenceRecord
     */
    public CaseEvidenceRecord(Integer id, Integer case_, String evidence) {
        super(CaseEvidence.CASE_EVIDENCE);

        set(0, id);
        set(1, case_);
        set(2, evidence);
    }
}
