/*
 * This file is generated by jOOQ.
 */
package au.edu.unimelb.crbilby.db.tables.records;


import au.edu.unimelb.crbilby.db.tables.Case;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * The table <code>cr_db.case</code>.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CaseRecord extends UpdatableRecordImpl<CaseRecord> implements Record10<Integer, String, Integer, String, Timestamp, String, Double, Double, Integer, Integer> {

    private static final long serialVersionUID = 1663757094;

    /**
     * Setter for <code>cr_db.case.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>cr_db.case.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>cr_db.case.profile</code>.
     */
    public void setProfile(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cr_db.case.profile</code>.
     */
    public String getProfile() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cr_db.case.type</code>.
     */
    public void setType(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>cr_db.case.type</code>.
     */
    public Integer getType() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>cr_db.case.address</code>.
     */
    public void setAddress(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cr_db.case.address</code>.
     */
    public String getAddress() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cr_db.case.date</code>.
     */
    public void setDate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>cr_db.case.date</code>.
     */
    public Timestamp getDate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>cr_db.case.description</code>.
     */
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>cr_db.case.description</code>.
     */
    public String getDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>cr_db.case.longitude</code>.
     */
    public void setLongitude(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>cr_db.case.longitude</code>.
     */
    public Double getLongitude() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>cr_db.case.latitude</code>.
     */
    public void setLatitude(Double value) {
        set(7, value);
    }

    /**
     * Getter for <code>cr_db.case.latitude</code>.
     */
    public Double getLatitude() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>cr_db.case.post</code>.
     */
    public void setPost(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>cr_db.case.post</code>.
     */
    public Integer getPost() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>cr_db.case.is_closed</code>.
     */
    public void setIsClosed(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>cr_db.case.is_closed</code>.
     */
    public Integer getIsClosed() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, Integer, String, Timestamp, String, Double, Double, Integer, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, Integer, String, Timestamp, String, Double, Double, Integer, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Case.CASE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Case.CASE.PROFILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Case.CASE.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Case.CASE.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Case.CASE.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Case.CASE.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field7() {
        return Case.CASE.LONGITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field8() {
        return Case.CASE.LATITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Case.CASE.POST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return Case.CASE.IS_CLOSED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getProfile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component7() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component8() {
        return getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getPost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getIsClosed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getProfile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value7() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value8() {
        return getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getPost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getIsClosed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CaseRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CaseRecord value2(String value) {
        setProfile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CaseRecord value3(Integer value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CaseRecord value4(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CaseRecord value5(Timestamp value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CaseRecord value6(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CaseRecord value7(Double value) {
        setLongitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CaseRecord value8(Double value) {
        setLatitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CaseRecord value9(Integer value) {
        setPost(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CaseRecord value10(Integer value) {
        setIsClosed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CaseRecord values(Integer value1, String value2, Integer value3, String value4, Timestamp value5, String value6, Double value7, Double value8, Integer value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CaseRecord
     */
    public CaseRecord() {
        super(Case.CASE);
    }

    /**
     * Create a detached, initialised CaseRecord
     */
    public CaseRecord(Integer id, String profile, Integer type, String address, Timestamp date, String description, Double longitude, Double latitude, Integer post, Integer isClosed) {
        super(Case.CASE);

        set(0, id);
        set(1, profile);
        set(2, type);
        set(3, address);
        set(4, date);
        set(5, description);
        set(6, longitude);
        set(7, latitude);
        set(8, post);
        set(9, isClosed);
    }
}
