/*
 * This file is generated by jOOQ.
 */
package au.edu.unimelb.crbilby.db.tables.records;


import au.edu.unimelb.crbilby.db.tables.CaseNotes;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * The table <code>cr_db.case_notes</code>.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CaseNotesRecord extends UpdatableRecordImpl<CaseNotesRecord> implements Record5<Integer, Integer, String, Timestamp, String> {

    private static final long serialVersionUID = 178597703;

    /**
     * Setter for <code>cr_db.case_notes.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>cr_db.case_notes.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>cr_db.case_notes.case</code>.
     */
    public void setCase(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>cr_db.case_notes.case</code>.
     */
    public Integer getCase() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>cr_db.case_notes.profile</code>.
     */
    public void setProfile(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>cr_db.case_notes.profile</code>.
     */
    public String getProfile() {
        return (String) get(2);
    }

    /**
     * Setter for <code>cr_db.case_notes.timestamp</code>.
     */
    public void setTimestamp(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>cr_db.case_notes.timestamp</code>.
     */
    public Timestamp getTimestamp() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>cr_db.case_notes.note</code>.
     */
    public void setNote(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>cr_db.case_notes.note</code>.
     */
    public String getNote() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, Timestamp, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, Timestamp, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CaseNotes.CASE_NOTES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return CaseNotes.CASE_NOTES.CASE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CaseNotes.CASE_NOTES.PROFILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return CaseNotes.CASE_NOTES.TIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return CaseNotes.CASE_NOTES.NOTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getCase();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getProfile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getNote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCase();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getProfile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getNote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CaseNotesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CaseNotesRecord value2(Integer value) {
        setCase(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CaseNotesRecord value3(String value) {
        setProfile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CaseNotesRecord value4(Timestamp value) {
        setTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CaseNotesRecord value5(String value) {
        setNote(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CaseNotesRecord values(Integer value1, Integer value2, String value3, Timestamp value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CaseNotesRecord
     */
    public CaseNotesRecord() {
        super(CaseNotes.CASE_NOTES);
    }

    /**
     * Create a detached, initialised CaseNotesRecord
     */
    public CaseNotesRecord(Integer id, Integer case_, String profile, Timestamp timestamp, String note) {
        super(CaseNotes.CASE_NOTES);

        set(0, id);
        set(1, case_);
        set(2, profile);
        set(3, timestamp);
        set(4, note);
    }
}
