/*
 * This file is generated by jOOQ.
 */
package au.edu.unimelb.crbilby.db.tables.records;


import au.edu.unimelb.crbilby.db.tables.LeaPost;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * The table <code>cr_db.lea_post</code>.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LeaPostRecord extends UpdatableRecordImpl<LeaPostRecord> implements Record2<String, Integer> {

    private static final long serialVersionUID = -1944458565;

    /**
     * Setter for <code>cr_db.lea_post.profile</code>.
     */
    public void setProfile(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>cr_db.lea_post.profile</code>.
     */
    public String getProfile() {
        return (String) get(0);
    }

    /**
     * Setter for <code>cr_db.lea_post.post</code>.
     */
    public void setPost(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>cr_db.lea_post.post</code>.
     */
    public Integer getPost() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return LeaPost.LEA_POST.PROFILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return LeaPost.LEA_POST.POST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getProfile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getPost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getProfile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LeaPostRecord value1(String value) {
        setProfile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LeaPostRecord value2(Integer value) {
        setPost(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LeaPostRecord values(String value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LeaPostRecord
     */
    public LeaPostRecord() {
        super(LeaPost.LEA_POST);
    }

    /**
     * Create a detached, initialised LeaPostRecord
     */
    public LeaPostRecord(String profile, Integer post) {
        super(LeaPost.LEA_POST);

        set(0, profile);
        set(1, post);
    }
}
