/*
 * This file is generated by jOOQ.
 */
package au.edu.unimelb.crbilby.db.tables.daos;


import au.edu.unimelb.crbilby.db.tables.CaseEvidence;
import au.edu.unimelb.crbilby.db.tables.records.CaseEvidenceRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * The table <code>cr_db.case_evidence</code>.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CaseEvidenceDao extends DAOImpl<CaseEvidenceRecord, au.edu.unimelb.crbilby.db.tables.pojos.CaseEvidence, Integer> {

    /**
     * Create a new CaseEvidenceDao without any configuration
     */
    public CaseEvidenceDao() {
        super(CaseEvidence.CASE_EVIDENCE, au.edu.unimelb.crbilby.db.tables.pojos.CaseEvidence.class);
    }

    /**
     * Create a new CaseEvidenceDao with an attached configuration
     */
    public CaseEvidenceDao(Configuration configuration) {
        super(CaseEvidence.CASE_EVIDENCE, au.edu.unimelb.crbilby.db.tables.pojos.CaseEvidence.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(au.edu.unimelb.crbilby.db.tables.pojos.CaseEvidence object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<au.edu.unimelb.crbilby.db.tables.pojos.CaseEvidence> fetchById(Integer... values) {
        return fetch(CaseEvidence.CASE_EVIDENCE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public au.edu.unimelb.crbilby.db.tables.pojos.CaseEvidence fetchOneById(Integer value) {
        return fetchOne(CaseEvidence.CASE_EVIDENCE.ID, value);
    }

    /**
     * Fetch records that have <code>case IN (values)</code>
     */
    public List<au.edu.unimelb.crbilby.db.tables.pojos.CaseEvidence> fetchByCase(Integer... values) {
        return fetch(CaseEvidence.CASE_EVIDENCE.CASE, values);
    }

    /**
     * Fetch records that have <code>evidence IN (values)</code>
     */
    public List<au.edu.unimelb.crbilby.db.tables.pojos.CaseEvidence> fetchByEvidence(String... values) {
        return fetch(CaseEvidence.CASE_EVIDENCE.EVIDENCE, values);
    }
}
