/*
 * This file is generated by jOOQ.
 */
package au.edu.unimelb.crbilby.db.tables.daos;


import au.edu.unimelb.crbilby.db.tables.Case;
import au.edu.unimelb.crbilby.db.tables.records.CaseRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * The table <code>cr_db.case</code>.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CaseDao extends DAOImpl<CaseRecord, au.edu.unimelb.crbilby.db.tables.pojos.Case, Integer> {

    /**
     * Create a new CaseDao without any configuration
     */
    public CaseDao() {
        super(Case.CASE, au.edu.unimelb.crbilby.db.tables.pojos.Case.class);
    }

    /**
     * Create a new CaseDao with an attached configuration
     */
    public CaseDao(Configuration configuration) {
        super(Case.CASE, au.edu.unimelb.crbilby.db.tables.pojos.Case.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(au.edu.unimelb.crbilby.db.tables.pojos.Case object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<au.edu.unimelb.crbilby.db.tables.pojos.Case> fetchById(Integer... values) {
        return fetch(Case.CASE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public au.edu.unimelb.crbilby.db.tables.pojos.Case fetchOneById(Integer value) {
        return fetchOne(Case.CASE.ID, value);
    }

    /**
     * Fetch records that have <code>profile IN (values)</code>
     */
    public List<au.edu.unimelb.crbilby.db.tables.pojos.Case> fetchByProfile(String... values) {
        return fetch(Case.CASE.PROFILE, values);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<au.edu.unimelb.crbilby.db.tables.pojos.Case> fetchByType(Integer... values) {
        return fetch(Case.CASE.TYPE, values);
    }

    /**
     * Fetch records that have <code>address IN (values)</code>
     */
    public List<au.edu.unimelb.crbilby.db.tables.pojos.Case> fetchByAddress(String... values) {
        return fetch(Case.CASE.ADDRESS, values);
    }

    /**
     * Fetch records that have <code>date IN (values)</code>
     */
    public List<au.edu.unimelb.crbilby.db.tables.pojos.Case> fetchByDate(Timestamp... values) {
        return fetch(Case.CASE.DATE, values);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<au.edu.unimelb.crbilby.db.tables.pojos.Case> fetchByDescription(String... values) {
        return fetch(Case.CASE.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>longitude IN (values)</code>
     */
    public List<au.edu.unimelb.crbilby.db.tables.pojos.Case> fetchByLongitude(Double... values) {
        return fetch(Case.CASE.LONGITUDE, values);
    }

    /**
     * Fetch records that have <code>latitude IN (values)</code>
     */
    public List<au.edu.unimelb.crbilby.db.tables.pojos.Case> fetchByLatitude(Double... values) {
        return fetch(Case.CASE.LATITUDE, values);
    }

    /**
     * Fetch records that have <code>post IN (values)</code>
     */
    public List<au.edu.unimelb.crbilby.db.tables.pojos.Case> fetchByPost(Integer... values) {
        return fetch(Case.CASE.POST, values);
    }

    /**
     * Fetch records that have <code>is_closed IN (values)</code>
     */
    public List<au.edu.unimelb.crbilby.db.tables.pojos.Case> fetchByIsClosed(Integer... values) {
        return fetch(Case.CASE.IS_CLOSED, values);
    }
}
