/*
 * This file is generated by jOOQ.
 */
package au.edu.unimelb.crbilby.db.tables.daos;


import au.edu.unimelb.crbilby.db.tables.CaseOtherCrimes;
import au.edu.unimelb.crbilby.db.tables.records.CaseOtherCrimesRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * The table <code>cr_db.case_other_crimes</code>.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CaseOtherCrimesDao extends DAOImpl<CaseOtherCrimesRecord, au.edu.unimelb.crbilby.db.tables.pojos.CaseOtherCrimes, Integer> {

    /**
     * Create a new CaseOtherCrimesDao without any configuration
     */
    public CaseOtherCrimesDao() {
        super(CaseOtherCrimes.CASE_OTHER_CRIMES, au.edu.unimelb.crbilby.db.tables.pojos.CaseOtherCrimes.class);
    }

    /**
     * Create a new CaseOtherCrimesDao with an attached configuration
     */
    public CaseOtherCrimesDao(Configuration configuration) {
        super(CaseOtherCrimes.CASE_OTHER_CRIMES, au.edu.unimelb.crbilby.db.tables.pojos.CaseOtherCrimes.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(au.edu.unimelb.crbilby.db.tables.pojos.CaseOtherCrimes object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<au.edu.unimelb.crbilby.db.tables.pojos.CaseOtherCrimes> fetchById(Integer... values) {
        return fetch(CaseOtherCrimes.CASE_OTHER_CRIMES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public au.edu.unimelb.crbilby.db.tables.pojos.CaseOtherCrimes fetchOneById(Integer value) {
        return fetchOne(CaseOtherCrimes.CASE_OTHER_CRIMES.ID, value);
    }

    /**
     * Fetch records that have <code>crime IN (values)</code>
     */
    public List<au.edu.unimelb.crbilby.db.tables.pojos.CaseOtherCrimes> fetchByCrime(String... values) {
        return fetch(CaseOtherCrimes.CASE_OTHER_CRIMES.CRIME, values);
    }
}
