/*
 * This file is generated by jOOQ.
 */
package au.edu.unimelb.crbilby.db.tables.daos;


import au.edu.unimelb.crbilby.db.tables.CaseAssign;
import au.edu.unimelb.crbilby.db.tables.records.CaseAssignRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * The table <code>cr_db.case_assign</code>.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CaseAssignDao extends DAOImpl<CaseAssignRecord, au.edu.unimelb.crbilby.db.tables.pojos.CaseAssign, Record2<Integer, String>> {

    /**
     * Create a new CaseAssignDao without any configuration
     */
    public CaseAssignDao() {
        super(CaseAssign.CASE_ASSIGN, au.edu.unimelb.crbilby.db.tables.pojos.CaseAssign.class);
    }

    /**
     * Create a new CaseAssignDao with an attached configuration
     */
    public CaseAssignDao(Configuration configuration) {
        super(CaseAssign.CASE_ASSIGN, au.edu.unimelb.crbilby.db.tables.pojos.CaseAssign.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Integer, String> getId(au.edu.unimelb.crbilby.db.tables.pojos.CaseAssign object) {
        return compositeKeyRecord(object.getCase(), object.getProfile());
    }

    /**
     * Fetch records that have <code>case IN (values)</code>
     */
    public List<au.edu.unimelb.crbilby.db.tables.pojos.CaseAssign> fetchByCase(Integer... values) {
        return fetch(CaseAssign.CASE_ASSIGN.CASE, values);
    }

    /**
     * Fetch records that have <code>profile IN (values)</code>
     */
    public List<au.edu.unimelb.crbilby.db.tables.pojos.CaseAssign> fetchByProfile(String... values) {
        return fetch(CaseAssign.CASE_ASSIGN.PROFILE, values);
    }
}
