/*
 * This file is generated by jOOQ.
 */
package au.edu.unimelb.crbilby.db.tables.daos;


import au.edu.unimelb.crbilby.db.tables.CrimeType;
import au.edu.unimelb.crbilby.db.tables.records.CrimeTypeRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * The table <code>cr_db.crime_type</code>.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CrimeTypeDao extends DAOImpl<CrimeTypeRecord, au.edu.unimelb.crbilby.db.tables.pojos.CrimeType, Integer> {

    /**
     * Create a new CrimeTypeDao without any configuration
     */
    public CrimeTypeDao() {
        super(CrimeType.CRIME_TYPE, au.edu.unimelb.crbilby.db.tables.pojos.CrimeType.class);
    }

    /**
     * Create a new CrimeTypeDao with an attached configuration
     */
    public CrimeTypeDao(Configuration configuration) {
        super(CrimeType.CRIME_TYPE, au.edu.unimelb.crbilby.db.tables.pojos.CrimeType.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(au.edu.unimelb.crbilby.db.tables.pojos.CrimeType object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<au.edu.unimelb.crbilby.db.tables.pojos.CrimeType> fetchById(Integer... values) {
        return fetch(CrimeType.CRIME_TYPE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public au.edu.unimelb.crbilby.db.tables.pojos.CrimeType fetchOneById(Integer value) {
        return fetchOne(CrimeType.CRIME_TYPE.ID, value);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<au.edu.unimelb.crbilby.db.tables.pojos.CrimeType> fetchByType(String... values) {
        return fetch(CrimeType.CRIME_TYPE.TYPE, values);
    }
}
