/*
 * This file is generated by jOOQ.
 */
package au.edu.unimelb.crbilby.db.tables.daos;


import au.edu.unimelb.crbilby.db.tables.LeaPost;
import au.edu.unimelb.crbilby.db.tables.records.LeaPostRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * The table <code>cr_db.lea_post</code>.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LeaPostDao extends DAOImpl<LeaPostRecord, au.edu.unimelb.crbilby.db.tables.pojos.LeaPost, Record2<String, Integer>> {

    /**
     * Create a new LeaPostDao without any configuration
     */
    public LeaPostDao() {
        super(LeaPost.LEA_POST, au.edu.unimelb.crbilby.db.tables.pojos.LeaPost.class);
    }

    /**
     * Create a new LeaPostDao with an attached configuration
     */
    public LeaPostDao(Configuration configuration) {
        super(LeaPost.LEA_POST, au.edu.unimelb.crbilby.db.tables.pojos.LeaPost.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<String, Integer> getId(au.edu.unimelb.crbilby.db.tables.pojos.LeaPost object) {
        return compositeKeyRecord(object.getProfile(), object.getPost());
    }

    /**
     * Fetch records that have <code>profile IN (values)</code>
     */
    public List<au.edu.unimelb.crbilby.db.tables.pojos.LeaPost> fetchByProfile(String... values) {
        return fetch(LeaPost.LEA_POST.PROFILE, values);
    }

    /**
     * Fetch records that have <code>post IN (values)</code>
     */
    public List<au.edu.unimelb.crbilby.db.tables.pojos.LeaPost> fetchByPost(Integer... values) {
        return fetch(LeaPost.LEA_POST.POST, values);
    }
}
