/*
 * This file is generated by jOOQ.
 */
package au.edu.unimelb.crbilby.db.tables.daos;


import au.edu.unimelb.crbilby.db.tables.Profile;
import au.edu.unimelb.crbilby.db.tables.records.ProfileRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * The table <code>cr_db.profile</code>.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfileDao extends DAOImpl<ProfileRecord, au.edu.unimelb.crbilby.db.tables.pojos.Profile, String> {

    /**
     * Create a new ProfileDao without any configuration
     */
    public ProfileDao() {
        super(Profile.PROFILE, au.edu.unimelb.crbilby.db.tables.pojos.Profile.class);
    }

    /**
     * Create a new ProfileDao with an attached configuration
     */
    public ProfileDao(Configuration configuration) {
        super(Profile.PROFILE, au.edu.unimelb.crbilby.db.tables.pojos.Profile.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(au.edu.unimelb.crbilby.db.tables.pojos.Profile object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<au.edu.unimelb.crbilby.db.tables.pojos.Profile> fetchById(String... values) {
        return fetch(Profile.PROFILE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public au.edu.unimelb.crbilby.db.tables.pojos.Profile fetchOneById(String value) {
        return fetchOne(Profile.PROFILE.ID, value);
    }

    /**
     * Fetch records that have <code>first_name IN (values)</code>
     */
    public List<au.edu.unimelb.crbilby.db.tables.pojos.Profile> fetchByFirstName(String... values) {
        return fetch(Profile.PROFILE.FIRST_NAME, values);
    }

    /**
     * Fetch records that have <code>last_name IN (values)</code>
     */
    public List<au.edu.unimelb.crbilby.db.tables.pojos.Profile> fetchByLastName(String... values) {
        return fetch(Profile.PROFILE.LAST_NAME, values);
    }

    /**
     * Fetch records that have <code>phone IN (values)</code>
     */
    public List<au.edu.unimelb.crbilby.db.tables.pojos.Profile> fetchByPhone(String... values) {
        return fetch(Profile.PROFILE.PHONE, values);
    }

    /**
     * Fetch records that have <code>role IN (values)</code>
     */
    public List<au.edu.unimelb.crbilby.db.tables.pojos.Profile> fetchByRole(Integer... values) {
        return fetch(Profile.PROFILE.ROLE, values);
    }
}
