/*
 * This file is generated by jOOQ.
 */
package au.edu.unimelb.crbilby.db;


import au.edu.unimelb.crbilby.db.tables.Case;
import au.edu.unimelb.crbilby.db.tables.CaseAssign;
import au.edu.unimelb.crbilby.db.tables.CaseEvidence;
import au.edu.unimelb.crbilby.db.tables.CaseNotes;
import au.edu.unimelb.crbilby.db.tables.CaseOtherCrimes;
import au.edu.unimelb.crbilby.db.tables.CrimeType;
import au.edu.unimelb.crbilby.db.tables.EscalateLevel;
import au.edu.unimelb.crbilby.db.tables.LeaPost;
import au.edu.unimelb.crbilby.db.tables.Post;
import au.edu.unimelb.crbilby.db.tables.Profile;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in cr_db
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>cr_db.case</code>.
     */
    public static final Case CASE = au.edu.unimelb.crbilby.db.tables.Case.CASE;

    /**
     * The table <code>cr_db.case_assign</code>.
     */
    public static final CaseAssign CASE_ASSIGN = au.edu.unimelb.crbilby.db.tables.CaseAssign.CASE_ASSIGN;

    /**
     * The table <code>cr_db.case_evidence</code>.
     */
    public static final CaseEvidence CASE_EVIDENCE = au.edu.unimelb.crbilby.db.tables.CaseEvidence.CASE_EVIDENCE;

    /**
     * The table <code>cr_db.case_notes</code>.
     */
    public static final CaseNotes CASE_NOTES = au.edu.unimelb.crbilby.db.tables.CaseNotes.CASE_NOTES;

    /**
     * The table <code>cr_db.case_other_crimes</code>.
     */
    public static final CaseOtherCrimes CASE_OTHER_CRIMES = au.edu.unimelb.crbilby.db.tables.CaseOtherCrimes.CASE_OTHER_CRIMES;

    /**
     * The table <code>cr_db.crime_type</code>.
     */
    public static final CrimeType CRIME_TYPE = au.edu.unimelb.crbilby.db.tables.CrimeType.CRIME_TYPE;

    /**
     * The table <code>cr_db.Escalate_level</code>.
     */
    public static final EscalateLevel ESCALATE_LEVEL = au.edu.unimelb.crbilby.db.tables.EscalateLevel.ESCALATE_LEVEL;

    /**
     * The table <code>cr_db.lea_post</code>.
     */
    public static final LeaPost LEA_POST = au.edu.unimelb.crbilby.db.tables.LeaPost.LEA_POST;

    /**
     * The table <code>cr_db.post</code>.
     */
    public static final Post POST = au.edu.unimelb.crbilby.db.tables.Post.POST;

    /**
     * The table <code>cr_db.profile</code>.
     */
    public static final Profile PROFILE = au.edu.unimelb.crbilby.db.tables.Profile.PROFILE;
}
